{"name": "test_add5[空格]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'", "trace": "self = <testing.test_calc.TestCalc object at 0x10a8ccc50>, get_calc = <python_code.calc.Calculator object at 0x10a8da7d0>, get_add_datas = [' ', 5, '请输入数字']\n\n    @pytest.mark.add\n    def test_add5(self,get_calc, get_add_datas):\n        result = None\n        try:\n            result = get_calc.add(get_add_datas[0],get_add_datas[1])\n            if isinstance(result,float):\n                result = round(result,2)\n        except Exception as e:\n            print(e)\n>       assert result == get_add_datas[2]\nE       AssertionError: assert None == '请输入数字'\n\ntest_calc.py:70: AssertionError"}, "parameters": [{"name": "get_add_datas", "value": "[' ', 5, '请输入数字']"}], "start": 1679561814610, "stop": 1679561814610, "uuid": "1fbecd9c-0429-4b89-9b7d-6c82db51d55f", "historyId": "869951f5ac2e30c0e3690a2cbb5c4842", "testCaseId": "4823aab592c32c66a45f8899fa1c9cbf", "fullName": "test_calc.TestCalc#test_add5", "labels": [{"name": "tag", "value": "add"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MacBook-Pro-106.local"}, {"name": "thread", "value": "15142-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}